const THEME_CONFIG = {
	PRIMARY_COLOR: '#207d7c',
	SECONDARY_COLOR: '#fff',
	BG_COLOR: '#eee',
	PRIMARY_FONT_FAMILY: 'ComfortaaRegular',
	PRIMARY_FONT_SIZE: 16,
	ICON_SIZE: 22,
	DEFAULT_M_B: 10
};

export default THEME_CONFIG;
